### ISSUE TITLE
Separating folders

### ISSUE THREAD

**Issue by EdnilsonRobert** [ifcanduela/lessc-on-save#1]
Hi, Igor.

This is a great and very useful package.

Is there any way to save the .less and .css files in separated folders. E.g.:

./css
    [less] // directory
       |____ style.less // inside less directory
    style.css // outside less directory

Thanks in advance.

**Comment by ifcanduela** [comment]
Hi,

I just pushed v0.4 of the package with an option to add a prefix to the generated CSS file. It's a bit flimsy but it will work for you if you set the new `CSS file prefix` option to `../`.

Let me know how it goes!
